include:
  - board: nice_nano_v2
    shield: charybdis_left
  - board: nice_nano_v2
    shield: charybdis_right
    snippet: zmk-usb-logging
    
  - board: nice_nano_v2
    shield: settings_reset
    
  - board: nice_nano_v2
    shield: tester_pro_micro
